"""Pydantic models for agent output types — ComplianceAlert and BriefingSummary.

These models define the structured outputs produced by the Compliance Agent
and Briefing Agent (Phase 6). Stored as Neo4j nodes for audit trail.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class AlertType(str, Enum):
    """Types of compliance alerts."""

    CERTIFICATION_EXPIRED = "certification_expired"
    CERTIFICATION_EXPIRING = "certification_expiring"
    WORKER_NON_COMPLIANT = "worker_non_compliant"
    PROJECT_NON_COMPLIANT = "project_non_compliant"
    INSPECTION_FAILED = "inspection_failed"
    CORRECTIVE_ACTION_OVERDUE = "corrective_action_overdue"
    HAZARD_UNRESOLVED = "hazard_unresolved"


class AlertSeverity(str, Enum):
    """Severity levels for compliance alerts."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ComplianceAlert(BaseModel):
    """A structured compliance alert produced by the Compliance Agent.

    Stored as a ComplianceAlert node in Neo4j:
    (Company)-[:HAS_COMPLIANCE_ALERT]->(ComplianceAlert)

    Attributes:
        alert_id: Unique alert identifier.
        alert_type: Category of compliance issue.
        severity: Risk severity level.
        entity_id: ID of the entity that triggered the alert.
        entity_type: Type of entity (Worker, Project, Inspection, etc.).
        company_id: Tenant scope.
        project_id: Project context (if applicable).
        message: Human-readable alert description.
        details: Structured detail data (e.g., expired certs, failed items).
        graph_evidence: Graph traversal evidence supporting the alert.
        event_id: The event that triggered this alert (if event-driven).
        agent_id: The agent that produced this alert.
        created_at: When the alert was created.
    """

    alert_id: str
    alert_type: AlertType
    severity: AlertSeverity
    entity_id: str
    entity_type: str
    company_id: str
    project_id: str | None = None
    message: str
    details: dict[str, Any] = Field(default_factory=dict)
    graph_evidence: dict[str, Any] = Field(default_factory=dict)
    event_id: str | None = None
    agent_id: str
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class BriefingSummary(BaseModel):
    """A structured morning brief produced by the Briefing Agent.

    Attributes:
        briefing_id: Unique briefing identifier.
        project_id: The project this brief covers.
        project_name: Human-readable project name.
        company_id: Tenant scope.
        date: The date this brief covers (YYYY-MM-DD).
        alerts: List of compliance alerts included in the brief.
        structured_data: Raw structured data assembled from MCP tools.
        llm_summary: Natural language summary generated by the LLM.
        cost_cents: LLM generation cost in cents.
        model_id: The Anthropic model ID used for generation.
        agent_id: The agent that produced this brief.
        created_at: When the brief was created.
    """

    model_config = ConfigDict(protected_namespaces=())

    briefing_id: str
    project_id: str
    project_name: str = ""
    company_id: str
    date: str
    alerts: list[dict[str, Any]] = Field(default_factory=list)
    structured_data: dict[str, Any] = Field(default_factory=dict)
    llm_summary: str = ""
    cost_cents: float = 0.0
    model_id: str = ""
    agent_id: str
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
