"""PDF generation service for safety documents."""

import html
import logging
from datetime import datetime, timezone

from weasyprint import HTML

from app.models.company import Company
from app.models.document import Document, DocumentType

logger = logging.getLogger(__name__)

_DOCUMENT_TYPE_LABELS: dict[DocumentType, str] = {
    DocumentType.SSSP: "Site-Specific Safety Plan",
    DocumentType.JHA: "Job Hazard Analysis",
    DocumentType.TOOLBOX_TALK: "Toolbox Talk",
    DocumentType.INCIDENT_REPORT: "Incident Report",
    DocumentType.FALL_PROTECTION: "Fall Protection Plan",
}

_CSS = """\
@page {
    size: letter;
    margin: 0.75in 0.75in 1in 0.75in;
    @bottom-center {
        content: "Generated by SafetyForge  |  Page " counter(page) " of " counter(pages);
        font-size: 8pt;
        color: #888888;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }
}

body {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 10pt;
    line-height: 1.5;
    color: #1a1a1a;
}

.header {
    border-bottom: 3px solid #1e40af;
    padding-bottom: 16px;
    margin-bottom: 24px;
}

.header-brand {
    font-size: 22pt;
    font-weight: 700;
    color: #1e40af;
    letter-spacing: -0.5px;
    margin: 0 0 2px 0;
}

.header-tagline {
    font-size: 8pt;
    color: #6b7280;
    text-transform: uppercase;
    letter-spacing: 1.5px;
    margin: 0;
}

.document-title {
    font-size: 18pt;
    font-weight: 700;
    color: #111827;
    margin: 20px 0 6px 0;
}

.document-type-badge {
    display: inline-block;
    background-color: #dbeafe;
    color: #1e40af;
    font-size: 8pt;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    padding: 3px 10px;
    border-radius: 4px;
    margin-bottom: 20px;
}

.meta-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 24px;
    font-size: 9pt;
}

.meta-table td {
    padding: 6px 12px;
    border: 1px solid #e5e7eb;
    vertical-align: top;
}

.meta-table .label {
    background-color: #f9fafb;
    color: #4b5563;
    font-weight: 600;
    width: 28%;
    text-transform: uppercase;
    font-size: 7.5pt;
    letter-spacing: 0.5px;
}

.meta-table .value {
    color: #1f2937;
}

.company-info-grid {
    display: table;
    width: 100%;
    margin-bottom: 24px;
}

.company-info-row {
    display: table-row;
}

.company-info-cell {
    display: table-cell;
    width: 50%;
    vertical-align: top;
}

h2.section-heading {
    font-size: 13pt;
    font-weight: 700;
    color: #1e40af;
    border-bottom: 1.5px solid #bfdbfe;
    padding-bottom: 6px;
    margin: 28px 0 12px 0;
    page-break-after: avoid;
}

h3.subsection-heading {
    font-size: 11pt;
    font-weight: 600;
    color: #374151;
    margin: 18px 0 8px 0;
    page-break-after: avoid;
}

.section-content {
    margin-bottom: 12px;
    text-align: justify;
}

.section-content p {
    margin: 0 0 8px 0;
}

.osha-ref {
    display: inline-block;
    background-color: #fef3c7;
    color: #92400e;
    font-size: 7.5pt;
    font-weight: 600;
    padding: 2px 6px;
    border-radius: 3px;
    margin-left: 8px;
    vertical-align: middle;
}

ul, ol {
    margin: 4px 0 12px 0;
    padding-left: 24px;
}

li {
    margin-bottom: 4px;
}

table.content-table {
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
    font-size: 9pt;
}

table.content-table th {
    background-color: #1e40af;
    color: white;
    padding: 8px 10px;
    text-align: left;
    font-weight: 600;
    font-size: 8pt;
    text-transform: uppercase;
    letter-spacing: 0.3px;
}

table.content-table td {
    padding: 6px 10px;
    border: 1px solid #e5e7eb;
    vertical-align: top;
}

table.content-table tr:nth-child(even) td {
    background-color: #f9fafb;
}

.status-badge {
    display: inline-block;
    padding: 2px 8px;
    border-radius: 3px;
    font-size: 8pt;
    font-weight: 600;
    text-transform: uppercase;
}

.status-draft {
    background-color: #fef3c7;
    color: #92400e;
}

.status-final {
    background-color: #d1fae5;
    color: #065f46;
}

.status-archived {
    background-color: #e5e7eb;
    color: #4b5563;
}

.divider {
    border: none;
    border-top: 1px solid #e5e7eb;
    margin: 20px 0;
}
"""


def _escape(value: object) -> str:
    """HTML-escape a value, returning an empty string for None.

    Args:
        value: Any value to escape for safe HTML rendering.

    Returns:
        HTML-escaped string representation.
    """
    if value is None:
        return ""
    return html.escape(str(value))


def _format_datetime(dt: datetime | None) -> str:
    """Format a datetime for display in the PDF.

    Args:
        dt: A datetime object, or None.

    Returns:
        A human-readable date string, or 'N/A'.
    """
    if dt is None:
        return "N/A"
    return dt.strftime("%B %d, %Y at %I:%M %p UTC")


def _render_list_items(items: list) -> str:
    """Render a list of items as HTML list items.

    Args:
        items: List of string or dict items.

    Returns:
        HTML string of <li> elements.
    """
    parts: list[str] = []
    for item in items:
        if isinstance(item, dict):
            text = _escape(item.get("text", item.get("name", str(item))))
            parts.append(f"<li>{text}</li>")
        else:
            parts.append(f"<li>{_escape(item)}</li>")
    return "\n".join(parts)


def _render_table(table_data: dict) -> str:
    """Render a table dict with headers and rows as an HTML table.

    Args:
        table_data: Dict with 'headers' (list[str]) and 'rows' (list[list[str]]).

    Returns:
        HTML string for the table.
    """
    headers = table_data.get("headers", [])
    rows = table_data.get("rows", [])

    header_cells = "".join(f"<th>{_escape(h)}</th>" for h in headers)
    body_rows: list[str] = []
    for row in rows:
        cells = "".join(f"<td>{_escape(cell)}</td>" for cell in row)
        body_rows.append(f"<tr>{cells}</tr>")

    return (
        '<table class="content-table">'
        f"<thead><tr>{header_cells}</tr></thead>"
        f"<tbody>{''.join(body_rows)}</tbody>"
        "</table>"
    )


def _render_section_value(value: object) -> str:
    """Render a section content value to HTML based on its type.

    Handles strings, lists, dicts with table data, and nested dicts.

    Args:
        value: The content value to render.

    Returns:
        HTML string for the value.
    """
    if isinstance(value, str):
        paragraphs = value.strip().split("\n\n")
        rendered = "".join(f"<p>{_escape(p)}</p>" for p in paragraphs if p.strip())
        return f'<div class="section-content">{rendered}</div>'

    if isinstance(value, list):
        return f"<ul>{_render_list_items(value)}</ul>"

    if isinstance(value, dict):
        if "headers" in value and "rows" in value:
            return _render_table(value)

        parts: list[str] = []
        for sub_key, sub_value in value.items():
            heading = sub_key.replace("_", " ").title()
            osha_ref = ""
            if isinstance(sub_value, dict) and "osha_reference" in sub_value:
                osha_ref = (
                    f'<span class="osha-ref">'
                    f'OSHA {_escape(sub_value["osha_reference"])}'
                    f"</span>"
                )
                content = sub_value.get("content", sub_value)
                parts.append(
                    f'<h3 class="subsection-heading">{_escape(heading)}{osha_ref}</h3>'
                )
                parts.append(_render_section_value(content))
            else:
                parts.append(f'<h3 class="subsection-heading">{_escape(heading)}</h3>')
                parts.append(_render_section_value(sub_value))
        return "\n".join(parts)

    return f'<div class="section-content"><p>{_escape(value)}</p></div>'


def _render_sections(content: dict) -> str:
    """Render all top-level sections of a document's content to HTML.

    Args:
        content: The document content dict with section keys.

    Returns:
        HTML string for all sections.
    """
    if not content:
        return (
            '<div class="section-content">'
            "<p><em>No content has been generated for this document yet.</em></p>"
            "</div>"
        )

    parts: list[str] = []
    section_number = 1

    for key, value in content.items():
        heading = key.replace("_", " ").title()

        osha_ref = ""
        if isinstance(value, dict) and "osha_reference" in value:
            osha_ref = (
                f'<span class="osha-ref">'
                f'OSHA {_escape(value["osha_reference"])}'
                f"</span>"
            )
            inner_value = value.get("content", value)
        else:
            inner_value = value

        parts.append(
            f'<h2 class="section-heading">'
            f"{section_number}. {_escape(heading)}{osha_ref}"
            f"</h2>"
        )
        parts.append(_render_section_value(inner_value))
        section_number += 1

    return "\n".join(parts)


def _render_project_info(project_info: dict) -> str:
    """Render project info as meta-table rows.

    Args:
        project_info: The document's project_info dict.

    Returns:
        HTML string of table rows.
    """
    if not project_info:
        return ""

    rows: list[str] = []
    for key, value in project_info.items():
        label = key.replace("_", " ").title()
        display_value = _escape(value) if not isinstance(value, (list, dict)) else _escape(str(value))
        rows.append(
            f"<tr>"
            f'<td class="label">{_escape(label)}</td>'
            f'<td class="value">{display_value}</td>'
            f"</tr>"
        )
    return "\n".join(rows)


class PdfService:
    """Generates professional PDF documents from structured content.

    Converts a Document model and Company info into a branded PDF
    using WeasyPrint for HTML-to-PDF conversion.
    """

    def generate(self, document: Document, company: Company) -> bytes:
        """Generate a PDF from a document and its parent company info.

        Args:
            document: The Document model with content to render.
            company: The Company model for header/metadata info.

        Returns:
            PDF file contents as bytes.
        """
        doc_type_label = _DOCUMENT_TYPE_LABELS.get(
            document.document_type, document.document_type.value.replace("_", " ").title()
        )
        status_class = f"status-{document.status.value}"
        generated_at = _format_datetime(document.generated_at)
        created_at = _format_datetime(document.created_at)
        now_str = datetime.now(timezone.utc).strftime("%B %d, %Y at %I:%M %p UTC")

        sections_html = _render_sections(document.content)
        project_info_html = _render_project_info(document.project_info)

        html_content = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>{_CSS}</style>
</head>
<body>
    <div class="header">
        <p class="header-brand">SafetyForge</p>
        <p class="header-tagline">AI-Powered Safety Compliance</p>
    </div>

    <h1 class="document-title">{_escape(document.title)}</h1>
    <span class="document-type-badge">{_escape(doc_type_label)}</span>

    <table class="meta-table">
        <tr>
            <td class="label">Company</td>
            <td class="value">{_escape(company.name)}</td>
        </tr>
        <tr>
            <td class="label">Address</td>
            <td class="value">{_escape(company.address)}</td>
        </tr>
        <tr>
            <td class="label">License No.</td>
            <td class="value">{_escape(company.license_number)}</td>
        </tr>
        <tr>
            <td class="label">Contact</td>
            <td class="value">{_escape(company.owner_name)} &mdash; {_escape(company.phone)} &mdash; {_escape(company.email)}</td>
        </tr>
        <tr>
            <td class="label">Document Status</td>
            <td class="value"><span class="status-badge {status_class}">{_escape(document.status.value.upper())}</span></td>
        </tr>
        <tr>
            <td class="label">Created</td>
            <td class="value">{_escape(created_at)}</td>
        </tr>
        <tr>
            <td class="label">Generated</td>
            <td class="value">{_escape(generated_at)}</td>
        </tr>
        <tr>
            <td class="label">PDF Exported</td>
            <td class="value">{_escape(now_str)}</td>
        </tr>
        {project_info_html}
    </table>

    <hr class="divider">

    {sections_html}
</body>
</html>"""

        logger.info(
            "Generating PDF for document %s (type=%s, company=%s)",
            document.id,
            document.document_type.value,
            company.id,
        )

        pdf_bytes: bytes = HTML(string=html_content).write_pdf()
        logger.info(
            "PDF generated for document %s (%d bytes)",
            document.id,
            len(pdf_bytes),
        )
        return pdf_bytes
